version: '3'
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - database
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Cherfianadir2022@
      - MYSQL_DATABASE=iot_air_quality
    volumes:
      - mysql-db:/var/lib/mysql


volumes:
  mysql-db: