version: '3'
services:
  build:
    context: .
    args: 
      NODE_ENV: development
  node-app:
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev