version: '3'
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - database
  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=cherfianadir
    volumes:
      - mysql-db=/data/db
  mqtt:
    image: mjenz/rpi-mosquitto
    environment:
      - PORT=1883
      - MYSQL_USER=iot_enst
      - MYSQL_PASSWORD=cherfianadir
    
volumes:
  mysql-db: